#pragma once

typedef enum
{
    INSTRUMENT_PIANO,
    INSTRUMENT_CHROMATIC_PERCUSSION,
    INSTRUMENT_ORGAN,
    INSTRUMENT_GUITAR,
    INSTRUMENT_BASS,
    INSTRUMENT_STRINGS,
    INSTRUMENT_STRINGS_CONTINUED,
    INSTRUMENT_BRASS,
    INSTRUMENT_REED,
    INSTRUMENT_PIPE,
    INSTRUMENT_SYNTH_LEAD,
    INSTRUMENT_SYNTH_PAD,
    INSTRUMENT_SYNTH_EFFECTS,
    INSTRUMENT_ETHNIC,
    INSTRUMENT_PERCUSSIVE,
    INSTRUMENT_SOUND_EFFECTS,
}
Instrument;

static Instrument
(Instrument_FromId)
(const uint8_t bank)
{
    return bank / 8;
}
